const KEY='mymoney_v3';
const defaults={digital:0,cash:0,hidden:false,theme:'sun',mode:'light',scale:100,lang:'pt',transactions:[],categories:['Alimentação','Compras','Transporte','Lazer','Casa','Educação','Tecnologia','Viagem','Outros']};
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){}
let state={...defaults,...saved};
if(saved.theme==='dark'){state.mode='dark';state.theme='sun'}
let wallet='digital',view='wallet';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const T={pt:{wallets:'Carteiras',digital:'Digital',cash:'Física',balance:'Saldo disponível',statement:'Extrato',summary:'Resumo geral',recent:'Últimos movimentos',empty:'Nenhum lançamento ainda.',add:'O que você deseja fazer?',income:'Adicionar saldo',expense:'Adicionar gasto',transfer:'Transferir',value:'Valor',category:'Categoria',titleIn:'De onde veio?',titleOut:'Onde/O que foi?',date:'Data',note:'Nota (opcional)',saveIncome:'Adicionar saldo',saveExpense:'Adicionar gasto',from:'De',to:'Para',back:'Voltar',cancel:'Cancelar',themes:'Temas',display:'Exibição',scale:'Escala',categories:'Categorias',language:'Idioma',english:'English',portuguese:'Português',addCategory:'Adicionar categoria',themeTitle:'Tema',mode:'Aparência',light:'Claro',dark:'Escuro',sun:'C6 Yellow',ocean:'Ocean',forest:'Forest',violet:'Violet',rose:'Rose',close:'Fechar',delete:'Excluir',edit:'Editar',search:'Pesquisar por descrição ou categoria',transferTitle:'Transferência',insufficient:'Saldo insuficiente.',invalid:'Digite um valor válido.',sameWallet:'Escolha carteiras diferentes.',noSummary:'Ainda não há gastos para analisar.',allCategories:'Categorias',noCategories:'Nenhuma categoria.',saved:'Salvo'},en:{wallets:'Wallets',digital:'Digital',cash:'Cash',balance:'Available balance',statement:'Statement',summary:'Overview',recent:'Recent activity',empty:'No transactions yet.',add:'What would you like to do?',income:'Add money',expense:'Add expense',transfer:'Transfer',value:'Amount',category:'Category',titleIn:'Where did it come from?',titleOut:'Where/What was it?',date:'Date',note:'Note (optional)',saveIncome:'Add money',saveExpense:'Add expense',from:'From',to:'To',back:'Back',cancel:'Cancel',themes:'Themes',display:'Display',scale:'Scale',categories:'Categories',language:'Language',english:'English',portuguese:'Português',addCategory:'Add category',themeTitle:'Theme',mode:'Appearance',light:'Light',dark:'Dark',sun:'C6 Yellow',ocean:'Ocean',forest:'Forest',violet:'Violet',rose:'Rose',close:'Close',delete:'Delete',edit:'Edit',search:'Search description or category',transferTitle:'Transfer',insufficient:'Insufficient balance.',invalid:'Enter a valid amount.',sameWallet:'Choose different wallets.',noSummary:'No spending to analyze yet.',allCategories:'Categories',noCategories:'No categories.',saved:'Saved'}};
const t=k=>T[state.lang][k]||k;
const fmt=n=>state.hidden?'••••••':`$ ${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const bal=()=>wallet==='digital'?state.digital:state.cash;
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function themeClass(){return `theme-${state.theme} mode-${state.mode}`}
function render(){
 document.documentElement.lang=state.lang==='pt'?'pt-BR':'en';document.body.className=themeClass();document.documentElement.style.setProperty('--ui-scale',state.scale/100);
 $('#pageTitle').textContent=t('wallets');$('#balanceLabel').textContent=t('balance');$('#balance').textContent=fmt(bal());
 $('#walletTabs').innerHTML=`<button class="${wallet==='digital'?'active':''}" data-wallet="digital">💳 ${t('digital')}</button><button class="${wallet==='cash'?'active':''}" data-wallet="cash">💵 ${t('cash')}</button>`;
 $$('[data-wallet]').forEach(b=>b.onclick=()=>{wallet=b.dataset.wallet;view='wallet';transition(render)});
 $$('.bottom-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));
 if(view==='wallet')renderWallet();else if(view==='statement')renderStatement();else if(view==='summary')renderSummary();else renderSettings();
}
function transition(fn){const main=$('main');main.classList.add('page-out');setTimeout(()=>{fn();main.classList.remove('page-out');main.classList.add('page-in');setTimeout(()=>main.classList.remove('page-in'),240)},110)}
function renderWallet(){const ts=state.transactions.filter(x=>x.wallet===wallet).slice(-5).reverse();$('#content').innerHTML=`<div class="wallet-head"><div><span class="wallet-kicker">${wallet==='digital'?'Carteira Digital':'Carteira Física'}</span><strong>${wallet==='digital'?'Online':'Cédulas'}</strong></div><button class="mini-action" id="quickAdd">＋</button></div><div class="actions"><button class="action-main" data-view="statement">${t('statement')}</button><button class="action-small" data-view="summary">${t('summary')}</button></div><div class="card"><div class="section-title">${t('recent')}</div>${ts.length?ts.map(row).join(''):`<div class="empty">${t('empty')}</div>`}</div>`;$('#quickAdd').onclick=openPlus;$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;transition(render)});bindRows()}
function row(x){let sign=x.type==='in'?'+':x.type==='transfer'?'↔':'−';return `<div class="row"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.category)} · ${x.date}</div></div><div class="rightrow"><span class="amount ${x.type}">${sign} ${fmt(x.amount)}</span><button class="more" data-id="${x.id}">•••</button></div></div>`}
function bindRows(){$$('.more').forEach(b=>b.onclick=()=>txMenu(Number(b.dataset.id)))}
function renderStatement(){const ts=state.transactions.filter(x=>x.wallet===wallet).slice().reverse();$('#content').innerHTML=`<div class="card"><div class="section-title">${t('statement')}</div><input id="search" class="search" placeholder="🔎 ${t('search')}"><div id="list">${list(ts)}</div></div>`;$('#search').oninput=e=>{const q=e.target.value.toLowerCase();$('#list').innerHTML=list(ts.filter(x=>(x.title+' '+x.category).toLowerCase().includes(q)))};bindRows()}
function list(ts){return ts.length?ts.map(row).join(''):`<div class="empty">${t('empty')}</div>`}
function renderSummary(){const ts=state.transactions,outs=ts.filter(x=>x.type==='out'),ins=ts.filter(x=>x.type==='in');const map={};outs.forEach(x=>map[x.category]=(map[x.category]||0)+Number(x.amount));const cats=Object.entries(map).sort((a,b)=>b[1]-a[1]);const spent=outs.reduce((a,x)=>a+Number(x.amount),0),income=ins.reduce((a,x)=>a+Number(x.amount),0);const colors=['#f4d400','#4f8cff','#44b979','#9b72ff','#ff6f91','#ff9f43','#36c5f0','#8e8e93'];const grad=cats.length?cats.map(([,v],i)=>`${colors[i%colors.length]} ${spent?100*v/spent:0}%`).join(', '):'#dedede 0 100%';$('#content').innerHTML=`<div class="summary-note">${t('summary')} · Digital + ${t('cash')}</div><div class="summary-grid"><div><span>Entradas</span><b class="green">${fmt(income)}</b></div><div><span>Gastos</span><b class="red">${fmt(spent)}</b></div></div><div class="card chart-card"><div class="section-title">Gastos por categoria</div>${cats.length?`<div class="donut" style="background:conic-gradient(${grad})"><div>${fmt(spent)}</div></div><div class="legend">${cats.map((x,i)=>`<div><i style="background:${colors[i%colors.length]}"></i>${esc(x[0])}<span>${spent?Math.round(100*x[1]/spent):0}%</span></div>`).join('')}</div>`:`<div class="empty">${t('noSummary')}</div>`}</div>`}
function renderSettings(){$('#content').innerHTML=`<div class="settings-list"><div class="setting-group"><h3>${t('language')}</h3><div class="seg"><button class="${state.lang==='pt'?'on':''}" data-lang="pt">Português</button><button class="${state.lang==='en'?'on':''}" data-lang="en">English</button></div></div><div class="setting-group"><h3>${t('display')}</h3><button class="setting-row" id="themes">🎨 <span>${t('themes')}</span><b>›</b></button><button class="setting-row" id="mode">☀️ <span>${t('mode')}</span><b>${state.mode==='light'?t('light'):t('dark')} ›</b></button><button class="setting-row" id="scale">↕️ <span>${t('scale')}</span><b>${state.scale}% ›</b></button></div><div class="setting-group"><h3>${t('categories')}</h3><button class="setting-row" id="cats">🏷️ <span>${t('allCategories')}</span><b>${state.categories.length} ›</b></button></div></div>`;$$('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;save()});$('#themes').onclick=themePicker;$('#mode').onclick=modePicker;$('#scale').onclick=scalePicker;$('#cats').onclick=categoriesView}
function themePicker(){modal(`<h2>${t('themeTitle')}</h2>${[['sun',t('sun')],['ocean',t('ocean')],['forest',t('forest')],['violet',t('violet')],['rose',t('rose')]].map(x=>`<button class="theme-choice ${state.theme===x[0]?'chosen':''}" data-theme="${x[0]}"><i class="theme-dot ${x[0]}"></i>${x[1]}<b>›</b></button>`).join('')}<button class="cancel" id="close">${t('close')}</button>`);$$('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;save();closeModal()});$('#close').onclick=closeModal}
function modePicker(){modal(`<h2>${t('mode')}</h2><div class="seg big"><button data-mode="light" class="${state.mode==='light'?'on':''}">☀️ ${t('light')}</button><button data-mode="dark" class="${state.mode==='dark'?'on':''}">🌙 ${t('dark')}</button></div><button class="cancel" id="close">${t('close')}</button>`);$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;save();closeModal()});$('#close').onclick=closeModal}
function scalePicker(){modal(`<h2>${t('scale')}</h2><div class="scale-val">${state.scale}%</div><input id="scaleRange" type="range" min="85" max="115" step="5" value="${state.scale}"><button class="primary" id="applyScale">${t('saved')}</button><button class="cancel" id="close">${t('close')}</button>`);$('#scaleRange').oninput=e=>{$('.scale-val').textContent=e.target.value+'%'};$('#applyScale').onclick=()=>{state.scale=Number($('#scaleRange').value);save();closeModal()};$('#close').onclick=closeModal}
function categoriesView(){modal(`<h2>${t('allCategories')}</h2>${state.categories.map((c,i)=>`<div class="category-item"><span>${esc(c)}</span><button data-delcat="${i}">×</button></div>`).join('')}<button class="primary" id="addCat">＋ ${t('addCategory')}</button><button class="cancel" id="close">${t('close')}</button>`);$$('[data-delcat]').forEach(b=>b.onclick=()=>{if(state.categories.length>1){state.categories.splice(Number(b.dataset.delcat),1);save();categoriesView()}});$('#addCat').onclick=()=>{const c=prompt(t('addCategory'));if(c&&c.trim()){state.categories.push(c.trim());save();categoriesView()}};$('#close').onclick=closeModal}
function openPlus(){modal(`<h2>${t('add')}</h2><button class="menu-btn" data-act="in">💰 ${t('income')}</button><button class="menu-btn" data-act="out">💸 ${t('expense')}</button><button class="menu-btn" data-act="transfer">🔄 ${t('transfer')}</button><button class="cancel" id="close">${t('cancel')}</button>`);$$('[data-act]').forEach(b=>b.onclick=()=>b.dataset.act==='transfer'?transferForm():moneyForm(b.dataset.act));$('#close').onclick=closeModal}
function moneyForm(type,tx=null){const isIn=type==='in';const amount=tx?tx.amount:'';modal(`<h2>${isIn?'💰':'💸'} ${isIn?t('income'):t('expense')}</h2><div class="form"><label>${t('value')}</label><input id="amount" type="number" inputmode="decimal" step="0.01" min="0" value="${amount}" placeholder="0.00"><label>Carteira</label><select id="walletSel"><option value="digital" ${(!tx||tx.wallet==='digital')?'selected':''}>💳 ${t('digital')}</option><option value="cash" ${tx&&tx.wallet==='cash'?'selected':''}>💵 ${t('cash')}</option></select>${!isIn?`<label>${t('category')}</label><select id="category">${state.categories.map(c=>`<option ${tx&&tx.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select>`:''}<label>${isIn?t('titleIn'):t('titleOut')}</label><input id="title" value="${tx?esc(tx.title):''}"><label>${t('date')}</label><input id="date" type="date" value="${tx?tx.date:new Date().toISOString().slice(0,10)}"><label>${t('note')}</label><textarea id="note">${tx?esc(tx.note||''):''}</textarea><button class="primary" id="confirm">${tx?'Salvar':isIn?t('saveIncome'):t('saveExpense')}</button><button class="cancel" id="back">${t('back')}</button></div>`);$('#back').onclick=openPlus;$('#confirm').onclick=()=>{const a=Number($('#amount').value),w=$('#walletSel').value;if(!Number.isFinite(a)||a<=0)return alert(t('invalid'));if(tx){const old=tx.amount,delta=isIn?a-old:old-a;if(tx.wallet!==w){if(tx.wallet==='digital')state.digital-=isIn?old:-old;else state.cash-=isIn?old:-old;if(w==='digital')state.digital+=isIn?a:-a;else state.cash+=isIn?a:-a}else{if(w==='digital')state.digital+=isIn?delta:-delta;else state.cash+=isIn?delta:-delta}tx.amount=a;tx.wallet=w;tx.title=$('#title').value.trim()||'Sem descrição';tx.category=isIn?'Entrada':$('#category').value;tx.date=$('#date').value;tx.note=$('#note').value.trim()}else{if(w==='digital')state.digital+=isIn?a:-a;else state.cash+=isIn?a:-a;state.transactions.push({id:Date.now(),amount:a,wallet:w,type:isIn?'in':'out',title:$('#title').value.trim()||'Sem descrição',category:isIn?'Entrada':$('#category').value,date:$('#date').value,note:$('#note').value.trim()})}save();closeModal()}}
function transferForm(){modal(`<h2>🔄 ${t('transferTitle')}</h2><div class="form"><label>${t('from')}</label><select id="from"><option value="digital">💳 ${t('digital')}</option><option value="cash">💵 ${t('cash')}</option></select><label>${t('to')}</label><select id="to"><option value="cash">💵 ${t('cash')}</option><option value="digital">💳 ${t('digital')}</option></select><label>${t('value')}</label><input id="amount" type="number" inputmode="decimal" step="0.01" min="0"><label>${t('date')}</label><input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"><button class="primary" id="confirm">${t('transfer')}</button><button class="cancel" id="back">${t('back')}</button></div>`);$('#back').onclick=openPlus;$('#confirm').onclick=()=>{const from=$('#from').value,to=$('#to').value,a=Number($('#amount').value);if(from===to)return alert(t('sameWallet'));if(!Number.isFinite(a)||a<=0)return alert(t('invalid'));if((from==='digital'?state.digital:state.cash)<a)return alert(t('insufficient'));if(from==='digital'){state.digital-=a;state.cash+=a}else{state.cash-=a;state.digital+=a}state.transactions.push({id:Date.now(),amount:a,type:'transfer',wallet:from,from,to,title:`${from==='digital'?t('digital'):t('cash')} → ${to==='digital'?t('digital'):t('cash')}`,category:t('transfer'),date:$('#date').value});save();closeModal()}}
function txMenu(id){const tx=state.transactions.find(x=>x.id===id);if(!tx)return;modal(`<h2>${esc(tx.title)}</h2>${tx.type!=='transfer'?'<button class="menu-btn" id="edit">✏️ '+t('edit')+'</button>':''}<button class="menu-btn danger" id="del">🗑️ ${t('delete')}</button><button class="cancel" id="close">${t('cancel')}</button>`);if(tx.type!=='transfer')$('#edit').onclick=()=>{closeModal();moneyForm(tx.type,tx)};$('#del').onclick=()=>deleteTx(tx.id);$('#close').onclick=closeModal}
function deleteTx(id){const tx=state.transactions.find(x=>x.id===id);if(!tx)return;if(tx.type==='in'){if(tx.wallet==='digital')state.digital-=tx.amount;else state.cash-=tx.amount}else if(tx.type==='out'){if(tx.wallet==='digital')state.digital+=tx.amount;else state.cash+=tx.amount}else{if(tx.from==='digital'){state.digital+=tx.amount;state.cash-=tx.amount}else{state.cash+=tx.amount;state.digital-=tx.amount}}state.transactions=state.transactions.filter(x=>x.id!==id);save();closeModal()}
function modal(html){$('#sheet').innerHTML=html;$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('#plusBtn').onclick=openPlus;$('#hideBtn').onclick=()=>{state.hidden=!state.hidden;save()};$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$$('.bottom-btn').forEach(b=>b.onclick=()=>{view=b.dataset.nav;transition(render)});
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
