const KEY="mymoney_v2";
const defaults={digital:0,cash:0,hidden:false,theme:"sun",scale:100,lang:"pt",transactions:[],goals:[],categories:["Alimentação","Compras","Transporte","Lazer","Casa","Educação","Tecnologia","Viagem","Outros"]};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||"{}"));
let wallet="total",view="wallet";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const T={pt:{total:"Carteira Total",digital:"Carteira Digital",cash:"Carteira Física",balance:"Saldo disponível",statement:"Extrato",summary:"Resumo",add:"O que você deseja fazer?",income:"Adicionar saldo",expense:"Adicionar gasto",transfer:"Transferir",goals:"Metas",settings:"Configurações",wallet:"Carteira",search:"Pesquisar no extrato",recent:"Últimos movimentos",empty:"Nenhum lançamento ainda.",value:"Valor",category:"Categoria",titleIn:"De onde veio?",titleOut:"Onde/O que foi?",date:"Data",note:"Nota (opcional)",saveIncome:"Adicionar saldo",saveExpense:"Adicionar gasto",from:"De",to:"Para",transferBtn:"Transferir",back:"Voltar",cancel:"Cancelar",themes:"Temas",display:"Exibição",scale:"Escala",categories:"Categorias",language:"Idioma",english:"English",portuguese:"Português",addCategory:"Adicionar categoria",newGoal:"Adicionar meta",target:"Objetivo",current:"Atual",progress:"Progresso",month:"Este mês",spent:"Gasto",incomeTotal:"Entradas",topCategories:"Gastos por categoria",digitalShort:"Digital",cashShort:"Física",themeTitle:"Escolha seu tema",light:"Claro",dark:"Midnight",sun:"C6 Yellow",ocean:"Ocean",forest:"Forest",violet:"Violet",rose:"Rose",close:"Fechar",goalName:"Nome da meta",goalValue:"Valor da meta",goalCurrent:"Valor atual",addGoal:"Adicionar meta",delete:"Excluir",edit:"Editar",noGoals:"Nenhuma meta criada.",transferTitle:"Transferência",insufficient:"Saldo insuficiente.",invalid:"Digite um valor válido.",sameWallet:"Escolha carteiras diferentes.",saved:"Salvo"},en:{total:"Total Wallet",digital:"Digital Wallet",cash:"Cash Wallet",balance:"Available balance",statement:"Statement",summary:"Summary",add:"What would you like to do?",income:"Add money",expense:"Add expense",transfer:"Transfer",goals:"Goals",settings:"Settings",wallet:"Wallet",search:"Search statement",recent:"Recent activity",empty:"No transactions yet.",value:"Amount",category:"Category",titleIn:"Where did it come from?",titleOut:"Where/What was it?",date:"Date",note:"Note (optional)",saveIncome:"Add money",saveExpense:"Add expense",from:"From",to:"To",transferBtn:"Transfer",back:"Back",cancel:"Cancel",themes:"Themes",display:"Display",scale:"Scale",categories:"Categories",language:"Language",english:"English",portuguese:"Português",addCategory:"Add category",newGoal:"Add goal",target:"Target",current:"Current",progress:"Progress",month:"This month",spent:"Spent",incomeTotal:"Income",topCategories:"Spending by category",digitalShort:"Digital",cashShort:"Cash",themeTitle:"Choose your theme",light:"Light",dark:"Midnight",sun:"C6 Yellow",ocean:"Ocean",forest:"Forest",violet:"Violet",rose:"Rose",close:"Close",goalName:"Goal name",goalValue:"Goal amount",goalCurrent:"Current amount",addGoal:"Add goal",delete:"Delete",edit:"Edit",noGoals:"No goals yet.",transferTitle:"Transfer",insufficient:"Insufficient balance.",invalid:"Enter a valid amount.",sameWallet:"Choose different wallets.",saved:"Saved"}};
const t=k=>T[state.lang][k]||k;
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function total(){return state.digital+state.cash}
function money(n){return state.hidden?"••••••":`$ ${Number(n||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function bal(){return wallet==="digital"?state.digital:wallet==="cash"?state.cash:total()}
function name(){return wallet==="digital"?t("digital"):wallet==="cash"?t("cash"):t("total")}
function relevant(){return state.transactions.filter(x=>wallet==="total"||x.wallet===wallet)}
function themeClass(){return `theme-${state.theme}`}
function render(){$("#walletTabsTop").innerHTML=walletTabs();bindWallet();document.documentElement.style.setProperty("--scale",state.scale/100);document.body.className=themeClass();document.documentElement.lang=state.lang==="pt"?"pt-BR":"en";$("#pageTitle").textContent=name();$("#balance").textContent=money(bal());$("#split").innerHTML=wallet==="total"?`${t("digitalShort")} ${money(state.digital)} <span>•</span> ${t("cashShort")} ${money(state.cash)}`:"";$$('.bottom-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));if(view==="wallet")renderWallet();if(view==="statement")renderStatement();if(view==="summary")renderSummary();if(view==="goals")renderGoals();if(view==="settings")renderSettings();$$('.quick-actions button').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));}
function walletTabs(){return `<div class="wallet-tabs"><button class="${wallet==='digital'?'active':''}" data-wallet="digital">💳 ${t('digitalShort')}</button><button class="${wallet==='cash'?'active':''}" data-wallet="cash">💵 ${t('cashShort')}</button></div>`}
function renderWallet(){const ts=relevant().slice(-5).reverse();$("#content").innerHTML=`<div class="hero-actions"><button class="action-main" data-view="statement">${t('statement')}</button><button class="action-small" data-view="summary">${t('summary')}</button></div>${viewSummaryPlaceholder(ts)}`;$$('[data-wallet]').forEach(b=>b.onclick=()=>{wallet=b.dataset.wallet;view='wallet';render()});$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});}
function viewSummaryPlaceholder(ts){return `<div class="card"><div class="section-title">${t('recent')}</div>${ts.length?ts.map(row).join(''):`<div class="empty">${t('empty')}</div>`}</div>`}
function row(x){let sign=x.type==='in'?'+':x.type==='transfer'?'↔':'−';return `<div class="row" data-id="${x.id}"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.category)} · ${x.date}</div></div><div class="rightrow"><span class="amount ${x.type}">${sign} ${money(x.amount)}</span><button class="more" data-id="${x.id}">•••</button></div></div>`}
function renderStatement(){const ts=relevant().slice().reverse();$("#content").innerHTML=`<div class="card"><div class="section-title">${t('statement')}</div><input id="search" class="search" placeholder="🔎 ${t('search')}"><div id="list">${list(ts)}</div></div>`;bindWallet();$("#search").oninput=e=>{const q=e.target.value.toLowerCase();$("#list").innerHTML=list(ts.filter(x=>(x.title+" "+x.category).toLowerCase().includes(q)))}}
function list(ts){return ts.length?ts.map(row).join(''):`<div class="empty">${t('empty')}</div>`}
function bindWallet(){$$('[data-wallet]').forEach(b=>b.onclick=()=>{wallet=b.dataset.wallet;view='wallet';render()});$$('.more').forEach(b=>b.onclick=()=>txMenu(Number(b.dataset.id)))}
function renderSummary(){const ts=relevant();const outs=ts.filter(x=>x.type==='out');const ins=ts.filter(x=>x.type==='in');const map={};outs.forEach(x=>map[x.category]=(map[x.category]||0)+x.amount);const cats=Object.entries(map).sort((a,b)=>b[1]-a[1]);const totalOut=outs.reduce((a,x)=>a+x.amount,0);const grad=cats.length?cats.map(([,v],i)=>`${['#f4d400','#4f8cff','#44b979','#9b72ff','#ff6f91','#ff9f43','#36c5f0','#8e8e93'][i%8]} ${totalOut?100*v/totalOut:0}%`).join(', '):'#e8e8e5 0 100%';$("#content").innerHTML=`<div class="summary-grid"><div><span>${t('incomeTotal')}</span><b class="green">${money(ins.reduce((a,x)=>a+x.amount,0))}</b></div><div><span>${t('spent')}</span><b class="red">${money(totalOut)}</b></div></div><div class="card chart-card"><div class="section-title">${t('topCategories')}</div><div class="donut" style="background:conic-gradient(${grad})"><div>${money(totalOut)}</div></div><div class="legend">${cats.length?cats.map((x,i)=>`<div><i style="background:${['#f4d400','#4f8cff','#44b979','#9b72ff','#ff6f91','#ff9f43','#36c5f0','#8e8e93'][i%8]}"></i>${esc(x[0])}<span>${totalOut?Math.round(100*x[1]/totalOut):0}%</span></div>`).join(''):`<div class="empty">${t('empty')}</div>`}</div></div>`;bindWallet()}
function renderGoals(){$("#content").innerHTML=`<div class="card goals-card"><div class="card-head"><div class="section-title">${t('goals')}</div><button class="mini-primary" id="addGoal">＋ ${t('newGoal')}</button></div>${state.goals.length?state.goals.map(g=>{const p=Math.min(100,(g.current/g.target)*100);return `<div class="goal"><div class="goal-head"><b>${esc(g.name)}</b><span>${p.toFixed(0)}%</span></div><div class="progress"><i style="width:${p}%"></i></div><div class="muted">${money(g.current)} / ${money(g.target)}</div></div>`}).join(''):`<div class="empty">${t('noGoals')}</div>`}</div>`;$('#addGoal').onclick=goalForm}
function renderSettings(){$("#content").innerHTML=`<div class="settings-list"><div class="setting-group"><h3>${t('language')}</h3><div class="seg"><button class="${state.lang==='pt'?'on':''}" data-lang="pt">Português</button><button class="${state.lang==='en'?'on':''}" data-lang="en">English</button></div></div><div class="setting-group"><h3>${t('display')}</h3><button class="setting-row" id="themes">🎨 <span>${t('themes')}</span><b>›</b></button><button class="setting-row" id="scale">↕️ <span>${t('scale')}</span><b>${state.scale}% ›</b></button></div><div class="setting-group"><h3>${t('categories')}</h3><button class="setting-row" id="cats">🏷️ <span>${t('categories')}</span><b>${state.categories.length} ›</b></button></div></div>`;$$('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;save()});$('#themes').onclick=themePicker;$('#scale').onclick=scalePicker;$('#cats').onclick=categoriesView}
function themePicker(){modal(`<h2>${t('themeTitle')}</h2>${[['sun',t('sun')],['ocean',t('ocean')],['forest',t('forest')],['violet',t('violet')],['rose',t('rose')],['dark',t('dark')]].map(x=>`<button class="menu-btn theme-option" data-theme="${x[0]}">${x[1]} ${state.theme===x[0]?'✓':''}</button>`).join('')}<button class="cancel" id="close">${t('close')}</button>`);$$('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;save();closeModal()});$('#close').onclick=closeModal}
function scalePicker(){modal(`<h2>${t('scale')}</h2><div class="form"><input id="scaleRange" type="range" min="85" max="115" step="5" value="${state.scale}"><div id="scaleVal" class="scale-val">${state.scale}%</div><button class="primary" id="done">${t('saved')}</button></div>`);$('#scaleRange').oninput=e=>$('#scaleVal').textContent=e.target.value+'%';$('#done').onclick=()=>{state.scale=Number($('#scaleRange').value);save();closeModal()}}
function categoriesView(){modal(`<h2>${t('categories')}</h2>${state.categories.map((c,i)=>`<div class="category-item"><span>${esc(c)}</span><button data-delcat="${i}">×</button></div>`).join('')}<button class="primary" id="newCat">＋ ${t('addCategory')}</button><button class="cancel" id="close">${t('close')}</button>`);$$('[data-delcat]').forEach(b=>b.onclick=()=>{if(state.categories.length>1){state.categories.splice(Number(b.dataset.delcat),1);save();categoriesView()}});$('#newCat').onclick=()=>{const c=prompt(t('addCategory'));if(c&&c.trim()){state.categories.push(c.trim());save();categoriesView()}};$('#close').onclick=closeModal}
function goalForm(){modal(`<h2>🎯 ${t('addGoal')}</h2><div class="form"><label>${t('goalName')}</label><input id="gn"><label>${t('goalValue')}</label><input id="gt" type="number" step="0.01"><label>${t('goalCurrent')}</label><input id="gc" type="number" step="0.01" value="0"><button class="primary" id="saveGoal">${t('addGoal')}</button><button class="cancel" id="close">${t('cancel')}</button></div>`);$('#saveGoal').onclick=()=>{const n=$('#gn').value.trim(),target=Number($('#gt').value),current=Number($('#gc').value);if(!n||target<=0)return alert(t('invalid'));state.goals.push({id:Date.now(),name:n,target,current});save();closeModal()};$('#close').onclick=closeModal}
function openPlus(){modal(`<h2>${t('add')}</h2><button class="menu-btn" data-act="in">💰 ${t('income')}</button><button class="menu-btn" data-act="out">💸 ${t('expense')}</button><button class="menu-btn" data-act="transfer">🔄 ${t('transfer')}</button><button class="cancel" id="close">${t('cancel')}</button>`);$('#close').onclick=closeModal;$$('[data-act]').forEach(b=>b.onclick=()=>b.dataset.act==='transfer'?transferForm():moneyForm(b.dataset.act))}
function walletOptions(selected){return wallet==='total'?`<option value="digital" ${selected==='digital'?'selected':''}>${t('digitalShort')}</option><option value="cash" ${selected==='cash'?'selected':''}>${t('cashShort')}</option>`:`<option value="${wallet}">${wallet==='digital'?t('digitalShort'):t('cashShort')}</option>`}
function moneyForm(type,tx=null){const isIn=type==='in';modal(`<h2>${isIn?'💰 '+t('income'):'💸 '+t('expense')}</h2><div class="form"><label>${t('value')}</label><input id="amount" type="number" inputmode="decimal" step="0.01" min="0.01" value="${tx?tx.amount:''}" placeholder="0.00"><label>${t('wallet')}</label><select id="w">${walletOptions(tx?.wallet)}</select>${!isIn?`<label>${t('category')}</label><select id="cat">${state.categories.map(c=>`<option ${tx?.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select>`:''}<label>${isIn?t('titleIn'):t('titleOut')}</label><input id="title" value="${tx?esc(tx.title):''}"><label>${t('date')}</label><input id="date" type="date" value="${tx?.date||new Date().toISOString().slice(0,10)}"><label>${t('note')}</label><textarea id="note" rows="2">${tx?.note||''}</textarea><button class="primary" id="confirm">${isIn?t('saveIncome'):t('saveExpense')}</button><button class="cancel" id="back">${t('back')}</button></div>`);$('#back').onclick=openPlus;$('#confirm').onclick=()=>{const amount=Number($('#amount').value);if(!amount||amount<=0)return alert(t('invalid'));const w=$('#w').value;if(tx){const old=tx.wallet;const deltaOld=tx.type==='in'?-tx.amount:tx.amount;if(old==='digital')state.digital+=deltaOld;if(old==='cash')state.cash+=deltaOld;tx.amount=amount;tx.wallet=w;tx.title=$('#title').value.trim()||'—';tx.category=isIn?'Entrada':$('#cat').value;tx.date=$('#date').value;tx.note=$('#note').value.trim();const delta=tx.type==='in'?amount:-amount;if(w==='digital')state.digital+=delta;else state.cash+=delta}else{const newTx={id:Date.now(),amount,wallet:w,type:isIn?'in':'out',title:$('#title').value.trim()||'—',category:isIn?'Entrada':$('#cat').value,date:$('#date').value,note:$('#note').value.trim()};if(w==='digital')state.digital+=isIn?amount:-amount;else state.cash+=isIn?amount:-amount;state.transactions.push(newTx)}save();closeModal()}}
function transferForm(){modal(`<h2>🔄 ${t('transferTitle')}</h2><div class="form"><label>${t('from')}</label><select id="from"><option value="digital">${t('digitalShort')}</option><option value="cash">${t('cashShort')}</option></select><label>${t('to')}</label><select id="to"><option value="cash">${t('cashShort')}</option><option value="digital">${t('digitalShort')}</option></select><label>${t('value')}</label><input id="amount" type="number" inputmode="decimal" step="0.01" min="0.01"><label>${t('date')}</label><input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"><button class="primary" id="confirm">${t('transferBtn')}</button><button class="cancel" id="back">${t('back')}</button></div>`);$('#back').onclick=openPlus;$('#confirm').onclick=()=>{const from=$('#from').value,to=$('#to').value,a=Number($('#amount').value);if(from===to)return alert(t('sameWallet'));if(!a||a<=0)return alert(t('invalid'));if((from==='digital'?state.digital:state.cash)<a)return alert(t('insufficient'));if(from==='digital'){state.digital-=a;state.cash+=a}else{state.cash-=a;state.digital+=a}state.transactions.push({id:Date.now(),amount:a,type:'transfer',wallet:'transfer',from,to,title:`${from==='digital'?t('digitalShort'):t('cashShort')} → ${to==='digital'?t('digitalShort'):t('cashShort')}`,category:t('transfer'),date:$('#date').value});save();closeModal()}}
function txMenu(id){const tx=state.transactions.find(x=>x.id===id);if(!tx)return;const edit=tx.type!=='transfer'?`<button class="menu-btn" id="edit">✏️ ${t('edit')}</button>`:'';modal(`<h2>${esc(tx.title)}</h2>${edit}<button class="menu-btn danger" id="del">🗑️ ${t('delete')}</button><button class="cancel" id="close">${t('cancel')}</button>`);if(tx.type!=='transfer')$("#edit").onclick=()=>{closeModal();moneyForm(tx.type==='in'?'in':'out',tx)};$("#del").onclick=()=>deleteTx(tx.id);$("#close").onclick=closeModal}
function deleteTx(id){const tx=state.transactions.find(x=>x.id===id);if(!tx)return;if(tx.type==='transfer'){if(tx.from==='digital'){state.digital+=tx.amount;state.cash-=tx.amount}else{state.cash+=tx.amount;state.digital-=tx.amount}}else{const delta=tx.type==='in'?-tx.amount:tx.amount;if(tx.wallet==='digital')state.digital+=delta;else state.cash+=delta}state.transactions=state.transactions.filter(x=>x.id!==id);save();closeModal()}
function editTx(id){const tx=state.transactions.find(x=>x.id===id);if(!tx)return;moneyForm(tx.type==='in'?'in':'out',tx);}
function modal(html){$('#sheet').innerHTML=html;$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('#plusBtn').onclick=openPlus;$('#hideBtn').onclick=()=>{state.hidden=!state.hidden;save()};$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$$('.quick-actions button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
$$('.bottom-btn').forEach(b=>b.onclick=()=>{view=b.dataset.nav; if(view==='wallet')wallet='total'; render()});
render();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
